name: 'ci/cd react app'
on: [push]
jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
       steps:
        - name: Check out repository code  # this is array and this is show array element a[0]
          uses: actions/checkout@v4   #clone the repo in the os like ubuntu ,windows(bcz not use for prcoessor is slow)
        - name: here i am install 
          uses: actions/setup-node@v2
          with: 
            node-version: "18"
        - name: Install dependecies 
          run: npm install
        - name: Build Project
          run: npm run build   
          run: | 
            echo "hello world its github actions"

 